version: '3'

services:
  python:
    image: zenichi/second-layer-python:3.0.1
    build: ./python
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - python_data:/var/lib/python

  phpmyadmin:
    image: zenichi/second-layer-phpmyadmin:3.0.1
    build: ./phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
      PHP_UPLOAD_MAX_FILESIZE: 128M
      PHP_POST_MAX_SIZE: 128M
    ports:
      - "4080:80"
    depends_on:
      - mysql
    networks:
      - app_network
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  mysql:
    image: zenichi/second-layer-mysql:3.0.1
    build: ./mysql
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "43306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: zenichi/second-layer-nginx:3.0.1
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "48080:80"
    depends_on:
      - python
      - phpmyadmin
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  python_data:
  mysql_data:
