version: '3'

services:
  python:
    image: zenichi/second-layer-python:4.5.1
    build: ./python
    ports:
      - "48080:8080"
    networks:
      - app_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - PLATMOBLE_USER=${PLATMOBLE_USER}
      - PLATMOBLE_PASSWORD=${PLATMOBLE_PASSWORD}
      - PYTHON_ENV=${PYTHON_ENV}
      - SECURITY_MODE=${SECURITY_MODE}
      - NOTIFICATION_MODE=${NOTIFICATION_MODE}
      - TZ=America/Sao_Paulo
    volumes:
      - python_data:/var/lib/python

  phpmyadmin:
    image: zenichi/second-layer-phpmyadmin:3.0.1
    build: ./phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
      PHP_UPLOAD_MAX_FILESIZE: 128M
      PHP_POST_MAX_SIZE: 128M
    ports:
      - "4080:80"
    depends_on:
      - mysql
    networks:
      - app_network


  mysql:
    image: zenichi/second-layer-mysql:3.0.1
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
    ports:
      - "43306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: zenichi/second-layer-nginx:3.0.1
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "40080:80"
    depends_on:
      - python
      - phpmyadmin
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  python_data:
  mysql_data:
