version: '3.8'

services:
  mysql:
    image: zenichi/second-layer-mysql:latest
    restart: always
    env_file:
      - 'data/env.sql'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: zenichi/second-layer-phpmyadmin:latest
    ports:
      - "80:80"
    env_file:   
      - 'data/env.php'
    depends_on:
      - mysql

  python:
    image: zenichi/second-layer-python:latest
    restart: always
    expose: 
      - 8081
    env_file:
      - 'data/env.python'
    volumes:
      - python_data:/var/lib/python
    depends_on:
      - mysql

  nginx:
    image: zenichi/second-layer-nginx:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - python

volumes:
  mysql_data:
  python_data:
